server:
  port: 8080
spring:
  application:
    name: authentication
  datasource:
    password: 12QWaszx#
    url: jdbc:postgresql://localhost:5432/authentication
    username: vanderson
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
